# Proxy configuration
# Settings are read from proxy/env.local (generated by bootstrap)

# Load local proxy settings if present
if [ -f "$ZSH/proxy/env.local" ]; then
  source "$ZSH/proxy/env.local"
fi

# Auto-enable proxy if configured
if [ -n "$DOTFILES_PROXY_URL" ]; then
  export HTTP_PROXY="$DOTFILES_PROXY_URL"
  export HTTPS_PROXY="$DOTFILES_PROXY_URL"
  export http_proxy="$DOTFILES_PROXY_URL"
  export https_proxy="$DOTFILES_PROXY_URL"
  export NO_PROXY="localhost,127.0.0.1,*.local"
  export no_proxy="$NO_PROXY"
fi

# Proxy functions for manual toggle
proxy_on() {
  local PROXY_URL="${DOTFILES_PROXY_URL:-http://127.0.0.1:7890}"

  export HTTP_PROXY="$PROXY_URL"
  export HTTPS_PROXY="$PROXY_URL"
  export http_proxy="$PROXY_URL"
  export https_proxy="$PROXY_URL"
  export NO_PROXY="localhost,127.0.0.1,*.local"
  export no_proxy="$NO_PROXY"

  echo "✓ Proxy enabled: $PROXY_URL"
}

proxy_off() {
  unset HTTP_PROXY
  unset HTTPS_PROXY
  unset http_proxy
  unset https_proxy
  unset NO_PROXY
  unset no_proxy
  echo "✓ Proxy disabled"
}

proxy_status() {
  if [ -n "$HTTP_PROXY" ]; then
    echo "Proxy: $HTTP_PROXY"
  else
    echo "Proxy: disabled"
  fi
}

